INSERT INTO PLANTS (ID, NAME, QUANTITY, WATERING_FREQUENCY, HAS_FRUIT) VALUES (1, 'Banana Yucca', 5, 7, true);
INSERT INTO PLANTS (ID, NAME, QUANTITY, WATERING_FREQUENCY, HAS_FRUIT) VALUES (2, 'Calla Lily', 16, 4, false);
INSERT INTO PLANTS (ID, NAME, QUANTITY, WATERING_FREQUENCY, HAS_FRUIT) VALUES (3, 'Cherry Tree', 2, 3, false);